### ISSUE TITLE
大佬，请问代理怎么配置呀？

### ISSUE THREAD

**Issue by koking0** [Alpaca4610/nonebot_plugin_chatpdf#2]
买了一台阿里云硅谷的服务器，测试了一下可以请求OpenAI，但是想请教一下代理要怎么配置呀？

**Comment by Alpaca4610** [comment]
> 买了一台阿里云硅谷的服务器，测试了一下可以请求OpenAI，但是想请教一下代理要怎么配置呀？

在美国的服务器上部署的机器人可以直接跑插件，不用设置代理。如果机器人部署的环境在国内，则需要自己搭建科学上网工具，然后在客户端开启局域网共享功能，把本地代理地址填入配置文件中。
